### ISSUE TITLE
black background does not work

### ISSUE THREAD

**Issue by Rifju** [mrflashstudio/osu-hiddenhax#1]
**1.** black background does not work - https://youtu.be/bBJQIEVyLA8
**2.** In my opinion, the folder with background and approachcircle should have a randomly generated name to reduce the detectability

**Comment by mrflashstudio** [comment]
1. Set your background dim in hack's settings (Main menu -> Settings -> Change background dim level)
2. I don't think this can ever ban you, unless you submit score with this hack open without changing its filename first. But sure, i'll add it as an option, why not.

**Comment by mrflashstudio** [comment]
Added in 8aff361, not random names though but this should be enough for now.
If you have any more questions/suggestions create a new issue or reopen this one. Thanks!
