### ISSUE TITLE
Changing AR with this program?

### ISSUE THREAD

**Issue by freshfriedfish** [mrflashstudio/osu-hiddenhax#2]
Could you add a functionality to change the AR of a map using the storyboard? Basically, a circle could fade in 700ms(AR 8) before needing to be clicked, at the coordinate of a circle?

**Comment by mrflashstudio** [comment]
This is planned, yes. Will try to implement this feature in the next few days, I don't have much free time now.

**Comment by mrflashstudio** [comment]
Added in 4117473! AR setup menu will show up when generating new storyboard.
If you have any more questions/suggestions create a new issue or reopen this one. Thanks!
