### ISSUE TITLE
new release does not work "unhandled exception"

### ISSUE THREAD

**Issue by freshfriedfish** [mrflashstudio/osu-hiddenhax#4]
After choosing a .osu I get this error https://i.imgur.com/DEAABas.jpg

**Comment by mrflashstudio** [comment]
Uploaded fixed version. Redownload latest release.

**Comment by freshfriedfish** [comment]
I am on the latest version. Side note: the skin folder in the latest version is empty

**Comment by mrflashstudio** [comment]
Default skin files are now embedded with the .exe file! If you want to use your own skin, then just copy it's contents into the Skin folder.

**Comment by freshfriedfish** [comment]
erm, i am getting the bug on the latest version though

**Comment by mrflashstudio** [comment]
Investigating.

**Comment by mrflashstudio** [comment]
Can you please send a screenshot of the folder where you unpacked the archive with a hack?

**Comment by freshfriedfish** [comment]
![image](https://user-images.githubusercontent.com/33766008/68243253-1a450980-ffe0-11e9-9d6b-1ca834e705b2.png)
are you asking for this?

**Comment by mrflashstudio** [comment]
Sorry, screenshot of the files in this folder

**Comment by freshfriedfish** [comment]
![image](https://user-images.githubusercontent.com/33766008/68243382-609a6880-ffe0-11e9-951a-7b1da0048597.png)

**Comment by mrflashstudio** [comment]
You're not using the latest version. In case github for some reason hasn't updated download link in the releases, i'll attach latest release here.
[osu-hiddenhax.zip](https://github.com/mrflashstudio/osu-hiddenhax/files/3811061/osu-hiddenhax.zip)
Let me know if this issue is resolved.

**Comment by freshfriedfish** [comment]
yes, it works flawlessly. great job!
