### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by freshfriedfish** [mrflashstudio/osu-hiddenhax#7]
![osu!hiddenhax_2019-11-08_19-16-43](https://user-images.githubusercontent.com/33766008/68521323-f0087b80-026d-11ea-8fd3-701c3f96e8d8.png)

on these maps 
https://osu.ppy.sh/beatmapsets/456986#osu/979155
https://osu.ppy.sh/beatmapsets/765169#osu/1608832

**Comment by mrflashstudio** [comment]
Fixed in d617b36

**Comment by freshfriedfish** [comment]
could you compile this for me? i have no knowledge of c# xd

**Comment by mrflashstudio** [comment]
New release is up! https://github.com/mrflashstudio/osu-hiddenhax/releases/latest
